backend:
  name: git-gateway
  branch: main # O la rama que uses

media_folder: "public/images/uploads" # Donde se guardarán las imágenes
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Entradas del Blog"
    folder: "src/content/blog" # Ajusta según la carpeta de tu template
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha de Publicación", name: "pubDate", widget: "datetime" }
      - { label: "Descripción", name: "description", widget: "string" }
      - { label: "Autor", name: "author", widget: "string" }
      - { label: "Imagen de Portada", name: "image", widget: "image" }
      - { label: "Cuerpo", name: "body", widget: "markdown" }